# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
arr1=np.array([45,89,79,57,450])
arr1

# Create a 2-dimensional NumPy array using np.array()
arr2=np.array([[67,56,45],[7,88,6]])
arr2


array([[67, 56, 45],
       [ 7, 88,  6]])

In [7]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print("shape:",arr1.shape)
print("Num od dime",arr1.ndim)
print("datatyoe",arr1.dtype)
print("size",arr1.size)
print("type",type(arr1))

shape: (5,)
Num od dime 1
datatyoe int32
size 5
type <class 'numpy.ndarray'>


In [8]:
# Attributes of 2-dimensional array
print("shape",arr2.shape)
print("no of dim",arr2.ndim)
print("datatype",arr2.dtype)
print("size",arr2.size)
print("type",type(arr2))

shape (2, 3)
no of dim 2
datatype int32
size 6
type <class 'numpy.ndarray'>


In [9]:
# Create an array of shape (5, 5) with only ones
np.ones((5,5)).astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
# Create an array of shape (3, 3, 5) with only zeros
np.zeros((3,3,5)).astype(int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array=np.random.randint(10,size=(7,2))
random_array

array([[5, 3],
       [9, 4],
       [2, 2],
       [2, 6],
       [7, 1],
       [4, 2],
       [9, 9]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array=np.random.random((3,5))
random_array

array([[0.76840578, 0.08531622, 0.75583587, 0.51158076, 0.01481142],
       [0.71640789, 0.83504411, 0.11856957, 0.63039625, 0.26146396],
       [0.18728235, 0.32034315, 0.63856066, 0.09572304, 0.12608879]])

In [13]:
# Create an array of normally distributed random numbers
np.random.rand(int(input()),int(input()))

1
2


array([[0.38248703, 0.37806835]])

In [14]:
# Set the random seed to 42
np.random.seed(42)
np.random.randint(10,size=(4,6))

# Create a random array of numbers between 0 & 10 of size (4, 6)


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [15]:
# Copy the code from the cell above and run it again
np.random.seed(42)
ran=np.random.randint(10,size=(4,6))
ran

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [17]:
# Find the 0'th index of the latest array you created
ran[0,0]

6

In [18]:
# Get the first 2 rows of latest array you created
ran[0:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [19]:
# Get the first 2 values of the first 2 rows of the latest array
ran[:2,:2]

array([[6, 3],
       [2, 6]])

In [20]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
array1=np.random.randint(10,size=(3,5))
array2=np.ones((3,5)).astype(int)
print(array1)
print(array2)

[[8 0 9 2 6]
 [3 8 2 4 2]
 [6 4 8 6 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
# Add the two arrays together
sum=array1+array2
sum

array([[ 9,  1, 10,  3,  7],
       [ 4,  9,  3,  5,  3],
       [ 7,  5,  9,  7,  2]])

In [22]:
# Create another array of ones of shape (5, 3)
arr=np.ones((5,3))

In [24]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
arr+sum

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [25]:
# Do the same operation you just did but this time with a transpose on one array
a=arr+sum.T
a.astype(int)

array([[10,  5,  8],
       [ 2, 10,  6],
       [11,  4, 10],
       [ 4,  6,  8],
       [ 8,  4,  3]])

In [26]:
# Take the latest array to the power of 2 using the python way
b=a**2
b.astype(int)

array([[100,  25,  64],
       [  4, 100,  36],
       [121,  16, 100],
       [ 16,  36,  64],
       [ 64,  16,   9]])

In [29]:
# Do the same thing with numpy way
np.square(a).astype(int)

array([[100,  25,  64],
       [  4, 100,  36],
       [121,  16, 100],
       [ 16,  36,  64],
       [ 64,  16,   9]])

In [30]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
print("Mean: ",np.mean(b))
print("Min: ",np.min(b))
print("MAx: ",np.max(b))
print("Standard deviation: ",np.std(b))
print("variance: ",np.var(b))

    
                    

Mean:  51.4
Min:  4.0
MAx:  121.0
Standard deviation:  37.75499966891802
variance:  1425.4399999999996


In [32]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
a1=np.random.randint(10,size=(3,3))
a2=np.random.randint(10,size=(3,2))
                
print(a1)
print("\n")
print(a2)
                     

[[4 1 3]
 [6 7 2]
 [0 3 1]]


[[7 3]
 [1 5]
 [5 9]]


In [49]:
# Perform a dot product on the two newest arrays you created
np.dot(a1, a2)


array([[44, 44],
       [59, 71],
       [ 8, 24]])

# Create two arrays of random integers between 0 to 10 both of size (4, 3)

In [52]:
# Perform a hadamard product on the two newest arrays you created
m=np.random.randint(10,size=(4,3))
n=np.random.randint(10,size=(4,3))
print(m)
print(n)
m * n

[[1 4 7]
 [9 8 8]
 [0 8 6]
 [8 7 0]]
[[7 7 2]
 [0 7 2]
 [2 0 4]
 [9 6 9]]


array([[ 7, 28, 14],
       [ 0, 56, 16],
       [ 0,  0, 24],
       [72, 42,  0]])

In [58]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(a1,a2)


array([[44, 44],
       [59, 71],
       [ 8, 24]])

In [54]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
np.dot(m, n.T).astype(int)

array([[ 49,  42,  30,  96],
       [135,  72,  50, 201],
       [ 68,  68,  24, 102],
       [105,  49,  16, 114]])

In [61]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
p=np.random.randint(10,size=(3,4))
q=np.random.randict(10,size=(3,4))
print(p)
print("\n")
print(q)

AttributeError: module 'numpy.random' has no attribute 'randict'

In [56]:
# Compare the two arrays with '>', '<=' and '==' 
print(p>q)
print(p<=q)
print(p==q)

NameError: name 'q' is not defined

In [57]:
# Sort one of the arrays you just created in ascending order
np.sort(p)

array([[6, 7, 8, 8],
       [0, 1, 6, 6],
       [2, 4, 7, 7]])

In [41]:
# Sort the indexes of one of the arrays you just created
np.argsort(p)

array([[2, 0, 1, 3],
       [0, 2, 3, 1],
       [3, 0, 2, 1]], dtype=int64)

In [42]:
# Find the index with the maximum value in one of the arrays you've created
np.amax(p)

9

In [43]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(start=1,stop=100,step=10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [44]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(p,axis=1)

array([3, 1, 1], dtype=int64)

In [45]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(p,axis=0)

array([1, 0, 0, 2], dtype=int64)